package taurus;
import org.xml.sax.Attributes;

import conexoes.ConexaoSQLite;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author icest
 */
public class Despeza extends javax.swing.JFrame {
ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
    /**
     * Creates new form Despeza
     */
    public Despeza() {
        initComponents();
        pnlFunc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistro = new javax.swing.JPanel();
        txtNomeDes = new javax.swing.JTextField();
        txtValorDes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObsDes = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDataDes = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        pnlFunc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDesp = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegistro.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlRegistro.add(txtNomeDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 270, 30));
        pnlRegistro.add(txtValorDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 150, 30));

        txtObsDes.setColumns(20);
        txtObsDes.setRows(5);
        jScrollPane1.setViewportView(txtObsDes);

        pnlRegistro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 280, -1));

        jLabel2.setText("Nome");
        pnlRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 50, -1));

        jLabel3.setText("Valor R$:");
        pnlRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, -1));

        jLabel4.setText("OBS.:");
        pnlRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 50, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlRegistro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 296, 100, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Registrar Despeza");
        pnlRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 240, 50));

        try {
            txtDataDes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataDesActionPerformed(evt);
            }
        });
        pnlRegistro.add(txtDataDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 90, 30));

        jLabel5.setText("Data:");
        pnlRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 60, 20));

        jButton5.setBackground(new java.awt.Color(0, 0, 204));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Próximo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnlRegistro.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 336, 90, 30));

        getContentPane().add(pnlRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 12, 436, 380));

        pnlFunc.setBackground(new java.awt.Color(255, 255, 255));
        pnlFunc.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Despezas");
        pnlFunc.add(jLabel7);
        jLabel7.setBounds(90, 0, 270, 40);

        tblDesp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "VALOR", "OBS", "DATA"
            }
        ));
        jScrollPane2.setViewportView(tblDesp);

        pnlFunc.add(jScrollPane2);
        jScrollPane2.setBounds(20, 60, 400, 220);

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlFunc.add(jButton3);
        jButton3.setBounds(311, 290, 100, 40);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnlFunc.add(jButton4);
        jButton4.setBounds(20, 300, 63, 23);

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlFunc.add(jButton2);
        jButton2.setBounds(10, 340, 90, 30);

        getContentPane().add(pnlFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 440, 380));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/resumo-de-fundo-com-um-desenho-geometrico_1048-1511.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 529, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataDesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeDes.getText();
        String valor = txtValorDes.getText();
        String obs = txtObsDes.getText();
        String data = txtDataDes.getText();
        System.out.println(data);
        
        conexaoSQLite.conectar();

                
                String sqlInsert = "INSERT INTO despeza("
                + "cod_despeza,"
                + "nome,"
                + "valor,"
                + "obs,"
                + "data_despeza"        
                + ") VALUES(null,?,?,?,?);";


                PreparedStatement preparedStatement =  conexaoSQLite.criarPreparedStatement(sqlInsert);

                try{
                    
                   
                    preparedStatement.setString(1,nome);
                    preparedStatement.setString(2,valor);
                    preparedStatement.setString(3,obs);
                    preparedStatement.setString(4,data);

                   

                    int resultado = preparedStatement.executeUpdate();

                    if(resultado == 1){
                        JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
                    }else{
                        JOptionPane.showMessageDialog(null,"Falha no cadastro.Tente novamente.");
                    }

                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e);
                    
                }finally{
                    if(preparedStatement != null){
                        try {
                            preparedStatement.close();
                            conexaoSQLite.desconectar();
                            txtNomeDes.setText("");
                            txtValorDes.setText("");
                            txtObsDes.setText("");
                            txtDataDes.setText("");
                        } catch (SQLException ex) {
                            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    conexaoSQLite.desconectar();
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed
private void LimparTabela() {
        int linhas = 0;
        int colunas = 0;
        String zer = null;

        for (linhas = 0; linhas <= tblDesp.getRowCount() - 1; linhas++) {
            for (colunas = 0; colunas <= tblDesp.getColumnCount() - 1; colunas++) {
                tblDesp.setValueAt(zer, linhas, colunas);
            }
        }
       
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        LimparTabela();
        ResultSet resultSet = null;
        Statement statement = null;
        conexaoSQLite.conectar();

        statement = conexaoSQLite.criarStatement();
  
        
        try{
           
            String query = "SELECT * FROM despeza;";
            
            resultSet = statement.executeQuery(query);
            int i = 0;
                
            while(resultSet.next()){
               
                tblDesp.setValueAt((resultSet.getString("cod_despeza")),i,0);
                tblDesp.setValueAt((resultSet.getString("nome")),i,1);
                tblDesp.setValueAt((resultSet.getString("valor")),i,2);
                tblDesp.setValueAt((resultSet.getString("obs")),i,3);
                tblDesp.setValueAt((resultSet.getString("data_despeza")),i,4);
                i++;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Query de pesquisa nao executada.");
        }
        conexaoSQLite.desconectar();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        conexaoSQLite.conectar();

        
  
        String li = String.valueOf(tblDesp.getValueAt(tblDesp.getSelectedRow(),0));
        String query = "DELETE FROM despeza WHERE cod_despeza = ?;";
        PreparedStatement preparedStatement =  conexaoSQLite.criarPreparedStatement(query);
        try{
           
            preparedStatement.setString(1,li);

            int resultado = preparedStatement.executeUpdate();
            
            if(resultado == 1){
           JOptionPane.showMessageDialog(null,"Excluido com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null,"Falha na exclusão!");
            }
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Query de pesquisa nao executada.");
        }
        conexaoSQLite.desconectar();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        pnlFunc.setVisible(false);
        pnlRegistro.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        pnlFunc.setVisible(true);
        pnlRegistro.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Despeza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Despeza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Despeza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Despeza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Despeza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlFunc;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JTable tblDesp;
    private javax.swing.JFormattedTextField txtDataDes;
    private javax.swing.JTextField txtNomeDes;
    private javax.swing.JTextArea txtObsDes;
    private javax.swing.JTextField txtValorDes;
    // End of variables declaration//GEN-END:variables
}
