package taurus;
import org.xml.sax.Attributes;

import conexoes.ConexaoSQLite;
import java.awt.List;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.Arrays;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.JobName;
import javax.print.attribute.standard.MediaSizeName;
import javax.print.attribute.standard.OrientationRequested;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author icest
 */
public class Pedido extends javax.swing.JFrame {
ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
    /**
     * Creates new form Pedido
     */

    
    String[] vetor = new String[30];
    Float[] total = new Float[30];
    String[] produtos = new String[30];
    
    DefaultListModel lista = new DefaultListModel();
    int selecionado  = 0;

    Cliente pedidoC = new Cliente();
    Compra compra = new Compra();
        
   
    public Pedido() throws SQLException {
        initComponents();
        
         for(int c = 0;c < vetor.length;c++){
            
            lista.addElement(" "+vetor[c]);
            
        }
         
        txtPesquisa.disable();
        btnProcurar.disable();
        txtNome1234.disable();
        txtTel.disable();
        txtCel.disable();
        txtEnd.disable();
        txtObs.disable();
        btnOk.disable();
        pnlClientePedido.setVisible(false);
        pnlObs.setVisible(false);
        
        ProdutoDAO dao = new ProdutoDAO();
        
        for(Produto p: dao.read()){ 
            boxProd.addItem(p);
            
        }
        
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        pnlPedido = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioSim = new javax.swing.JRadioButton();
        radioNao = new javax.swing.JRadioButton();
        btnCliOk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProd = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        boxProd = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnEnviar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        radioCartao = new javax.swing.JRadioButton();
        radioDin = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        btnObsPedido = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        btnRmv = new javax.swing.JButton();
        pnlObs = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObsPedido = new javax.swing.JTextArea();
        btnObsOk = new javax.swing.JButton();
        pnlClientePedido = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtNome1234 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTel = new javax.swing.JFormattedTextField();
        txtCel = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        txtId = new javax.swing.JLabel();
        btnProsseguir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jLabel20.setText("jLabel20");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPedido.setBackground(new java.awt.Color(255, 255, 255));
        pnlPedido.setLayout(null);
        pnlPedido.add(jSeparator1);
        jSeparator1.setBounds(0, 150, 530, 10);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pedido");
        pnlPedido.add(jLabel2);
        jLabel2.setBounds(140, 0, 230, 50);

        jLabel3.setText("Cliente Cadastrado?");
        pnlPedido.add(jLabel3);
        jLabel3.setBounds(20, 96, 130, 30);

        radioSim.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioSim);
        radioSim.setText("Sim");
        pnlPedido.add(radioSim);
        radioSim.setBounds(180, 100, 47, 24);

        radioNao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioNao);
        radioNao.setSelected(true);
        radioNao.setText("Não");
        pnlPedido.add(radioNao);
        radioNao.setBounds(240, 100, 47, 24);

        btnCliOk.setText("Prosseguir");
        btnCliOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliOkActionPerformed(evt);
            }
        });
        pnlPedido.add(btnCliOk);
        btnCliOk.setBounds(341, 96, 110, 30);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CLIENTE:");
        pnlPedido.add(jLabel4);
        jLabel4.setBounds(30, 50, 70, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("PRODUTO");
        pnlPedido.add(jLabel5);
        jLabel5.setBounds(40, 150, 80, 30);

        lstProd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lstProd.setModel(lista);
        lstProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstProd);

        pnlPedido.add(jScrollPane1);
        jScrollPane1.setBounds(290, 180, 230, 200);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pedidos:");
        pnlPedido.add(jLabel6);
        jLabel6.setBounds(290, 150, 230, 30);

        boxProd.setBackground(new java.awt.Color(255, 255, 255));
        boxProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProdActionPerformed(evt);
            }
        });
        pnlPedido.add(boxProd);
        boxProd.setBounds(40, 210, 180, 30);

        jLabel7.setText("Selecionar pedidos:");
        pnlPedido.add(jLabel7);
        jLabel7.setBounds(40, 180, 120, 30);

        txtQtd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        pnlPedido.add(txtQtd);
        txtQtd.setBounds(40, 280, 60, 30);

        jLabel8.setText("Quantidade:");
        pnlPedido.add(jLabel8);
        jLabel8.setBounds(40, 250, 90, 30);

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlPedido.add(btnAdd);
        btnAdd.setBounds(120, 270, 100, 40);
        pnlPedido.add(jSeparator2);
        jSeparator2.setBounds(0, 390, 530, 10);

        btnEnviar.setText("Enviar");
        btnEnviar.setToolTipText("");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        pnlPedido.add(btnEnviar);
        btnEnviar.setBounds(200, 560, 130, 40);

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("0.00");
        pnlPedido.add(lblTotal);
        lblTotal.setBounds(400, 410, 110, 70);

        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Total");
        pnlPedido.add(jLabel11);
        jLabel11.setBounds(390, 396, 40, 20);

        radioCartao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(radioCartao);
        radioCartao.setText("Cartão");
        radioCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCartaoActionPerformed(evt);
            }
        });
        pnlPedido.add(radioCartao);
        radioCartao.setBounds(40, 420, 63, 24);

        radioDin.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(radioDin);
        radioDin.setSelected(true);
        radioDin.setText("Dinheiro");
        radioDin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDinActionPerformed(evt);
            }
        });
        pnlPedido.add(radioDin);
        radioDin.setBounds(110, 420, 72, 24);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("PAGAMENTO");
        pnlPedido.add(jLabel12);
        jLabel12.setBounds(40, 390, 100, 30);
        pnlPedido.add(txtValor);
        txtValor.setBounds(40, 480, 140, 30);

        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText(" Valor R$:");
        pnlPedido.add(jLabel13);
        jLabel13.setBounds(40, 460, 70, 20);

        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        pnlPedido.add(btnCalc);
        btnCalc.setBounds(190, 480, 90, 30);

        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Troco");
        pnlPedido.add(jLabel14);
        jLabel14.setBounds(390, 470, 50, 30);

        lblTroco.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTroco.setText("0.00");
        pnlPedido.add(lblTroco);
        lblTroco.setBounds(400, 490, 120, 50);

        btnObsPedido.setBackground(new java.awt.Color(0, 0, 204));
        btnObsPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnObsPedido.setText("Observação");
        btnObsPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObsPedidoActionPerformed(evt);
            }
        });
        pnlPedido.add(btnObsPedido);
        btnObsPedido.setBounds(10, 570, 120, 26);

        lblCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(204, 0, 0));
        lblCliente.setText("nome");
        pnlPedido.add(lblCliente);
        lblCliente.setBounds(100, 50, 300, 30);

        btnRmv.setBackground(new java.awt.Color(204, 0, 0));
        btnRmv.setForeground(new java.awt.Color(255, 255, 255));
        btnRmv.setText("Remover");
        btnRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvActionPerformed(evt);
            }
        });
        pnlPedido.add(btnRmv);
        btnRmv.setBounds(120, 320, 100, 26);

        getContentPane().add(pnlPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 6, 550, 610));

        pnlObs.setBackground(new java.awt.Color(255, 255, 255));
        pnlObs.setLayout(null);

        jLabel21.setText("Observação");
        pnlObs.add(jLabel21);
        jLabel21.setBounds(20, 10, 90, 30);

        txtObsPedido.setColumns(20);
        txtObsPedido.setLineWrap(true);
        txtObsPedido.setRows(5);
        jScrollPane3.setViewportView(txtObsPedido);

        pnlObs.add(jScrollPane3);
        jScrollPane3.setBounds(20, 50, 490, 120);

        btnObsOk.setText("Prosseguir");
        btnObsOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObsOkActionPerformed(evt);
            }
        });
        pnlObs.add(btnObsOk);
        btnObsOk.setBounds(391, 176, 120, 30);

        getContentPane().add(pnlObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 550, 210));

        pnlClientePedido.setBackground(new java.awt.Color(255, 255, 255));
        pnlClientePedido.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cliente Pedido");
        pnlClientePedido.add(jLabel9);
        jLabel9.setBounds(140, 10, 190, 30);
        pnlClientePedido.add(txtPesquisa);
        txtPesquisa.setBounds(90, 60, 270, 30);

        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        pnlClientePedido.add(btnProcurar);
        btnProcurar.setBounds(370, 60, 90, 30);

        jLabel10.setText("Nome");
        pnlClientePedido.add(jLabel10);
        jLabel10.setBounds(40, 60, 50, 30);
        pnlClientePedido.add(jSeparator3);
        jSeparator3.setBounds(0, 112, 490, 10);
        pnlClientePedido.add(txtNome1234);
        txtNome1234.setBounds(90, 120, 280, 30);

        jLabel15.setText("Nome");
        pnlClientePedido.add(jLabel15);
        jLabel15.setBounds(40, 126, 50, 20);

        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlClientePedido.add(txtTel);
        txtTel.setBounds(90, 160, 110, 30);

        try {
            txtCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlClientePedido.add(txtCel);
        txtCel.setBounds(250, 160, 120, 30);

        jLabel16.setText("TeL.:");
        pnlClientePedido.add(jLabel16);
        jLabel16.setBounds(40, 160, 40, 30);

        jLabel17.setText("Cel.:");
        pnlClientePedido.add(jLabel17);
        jLabel17.setBounds(210, 160, 40, 30);
        pnlClientePedido.add(txtEnd);
        txtEnd.setBounds(90, 200, 280, 30);

        jLabel18.setText("End.:");
        pnlClientePedido.add(jLabel18);
        jLabel18.setBounds(41, 200, 50, 30);

        txtObs.setColumns(20);
        txtObs.setLineWrap(true);
        txtObs.setRows(5);
        jScrollPane2.setViewportView(txtObs);

        pnlClientePedido.add(jScrollPane2);
        jScrollPane2.setBounds(90, 240, 280, 83);

        jLabel19.setText("Obs.:");
        pnlClientePedido.add(jLabel19);
        jLabel19.setBounds(40, 236, 50, 20);

        btnOk.setText("Cadastrar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        pnlClientePedido.add(btnOk);
        btnOk.setBounds(380, 290, 100, 30);

        txtId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtId.setText("ID");
        pnlClientePedido.add(txtId);
        txtId.setBounds(20, 10, 50, 30);

        btnProsseguir.setText("Prosseguir");
        btnProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsseguirActionPerformed(evt);
            }
        });
        pnlClientePedido.add(btnProsseguir);
        btnProsseguir.setBounds(190, 340, 110, 30);

        getContentPane().add(pnlClientePedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 12, 540, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/resumo-de-fundo-com-um-desenho-geometrico_1048-1511.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
       int cnf = JOptionPane.showConfirmDialog(this,"Confirmar venda?");
       if(cnf == 0){
          
           ArrayList<String> agenda = new ArrayList();
            for(int i = 0;i < produtos.length;i++){
                if(!(produtos[i] == null)){
                    agenda.add(produtos[i]+"      "+format(total[i])+" \n");
                }    
            }
            
           
            
            compra.setProdutos(agenda.toString());
            
            
            if(radioDin.isSelected()){
                compra.setPagamento("DINHEIRO");
            }else{
                compra.setPagamento("CARTAO");
            }
            
           compra.setTroco(lblTroco.getText());
           compra.setData_compra(getDateTime());
           String data = dataBanco();
           compra.setStatus("EM ANDAMENTO");
           compra.getCliente();
           compra.setValor_compra(lblTotal.getText());
           compra.getObs();
           
           
           JOptionPane.showMessageDialog(null,
           "DATA: "+compra.getData_compra()+" \n"+
           "CLIENTE: "+compra.getCliente()+" \n"+
           "PAGAMENTO: "+compra.getPagamento()+" \n"+
           "TOTAL: "+compra.getValor_compra()+" \n"+
           "TROCO: "+compra.getTroco()+" \n"+
           "STATUS: "+compra.getStatus()+" \n"+
           "OBS: "+compra.getObs());
           
           
           
           System.out.printf("            TAURU'S          \n\r"
                        + "   RUA DAS PUTA, 38 , CARUARU   \n\r"
                        + "   CNPJ: 00.000.000/0001-00     \n\r"
                        + "   DATA: "+compra.getData_compra()+"\n\r"
                        + "CLIENTE: "+compra.getCliente()+"\n\r"
                        + "--------------------------------\n\r"
                        + "             RECIBO             \n\r"
                        + "--------------------------------\n\r"
                        + "                                \n\r"
                        + " TOTAL: "+compra.getValor_compra()+"\n\r"
                        + " PAGAMENTO: "+ compra.getPagamento()+"\n\r"
                        + " TROCO : "+ compra.getTroco()+"\n\r"
                        + "                                \n\r"
                        + "--------------------------------\n\r" 
                        + "PROD.    (QTD.)   PREÇO(R$) \n\r"
                        + " \b "+compra.getProdutos()+" \b          \n\r"
                        + "--------------------------------\n\r"
                        + "OBS: "+compra.getObs() +"\n\r"       
                        + " \n\r"
                        + "TAURU'S AGRADECE SUA PREFEREÊCIA"
                        + "\n\r\n\r\f");
           
           
           conexaoSQLite.conectar();

                String sqlInsert = "INSERT INTO compra("
                + "cod_compra,"        
                + "data_compra,"
                + "valor_compra,"
                + "cliente,"
                + "produtos,"
                + "obs,"
                + "status) VALUES(null,?,?,?,?,?,?);";

                PreparedStatement preparedStatement =  conexaoSQLite.criarPreparedStatement(sqlInsert);

                try{

                    preparedStatement.setString(1,data);
                    preparedStatement.setString(2,compra.getValor_compra());
                    preparedStatement.setString(3,compra.getCliente());
                    preparedStatement.setString(4,compra.getProdutos());
                    preparedStatement.setString(5,compra.getObs());
                    preparedStatement.setString(6,compra.getStatus());
                    
                    int resultado = preparedStatement.executeUpdate();

                    if(resultado == 1){
                        JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
                    }else{
                        JOptionPane.showMessageDialog(null,"Falha no cadastro.Tente novamente.");
                    }

                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Não foi possível cadastrar.");
                }finally{
                    if(preparedStatement != null){
                        try {
                            preparedStatement.close();
                            conexaoSQLite.desconectar();
                            this.dispose();
                        } catch (SQLException ex) {
                            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    conexaoSQLite.desconectar();
                }
                
                // \n\r para no no valinha e \f para nova pagina
                
                imprimir("            TAURU'S          \n\r"
                        + "   RUA DAS PUTA, 38 , CARUARU   \n\r"
                        + "   CNPJ: 00.000.000/0001-00     \n\r"
                        + "   DATA: "+compra.getData_compra()+"\n\r"
                        + "CLIENTE: "+compra.getCliente()+"\n\r"
                        + "--------------------------------\n\r"
                        + "             RECIBO             \n\r"
                        + "--------------------------------\n\r"
                        + "                                \n\r"
                        + " TOTAL: "+compra.getValor_compra()+"\n\r"
                        + " PAGAMENTO: "+ compra.getPagamento()+"\n\r"
                        + " TROCO : "+ compra.getTroco()+"\n\r"
                        + "                                \n\r"
                        + "--------------------------------\n\r" 
                        + "PROD.    (QTD.)   PREÇO(R$) \n\r"
                        + " \b "+compra.getProdutos()+" \b          \n\r"
                        + "--------------------------------\n\r"
                        + "OBS: "+compra.getObs() +"\n\r"       
                        + " \n\r"
                        + "TAURU'S AGRADECE SUA PREFEREÊCIA"
                        + "\n\r\n\r\f");
       }

        
    }//GEN-LAST:event_btnEnviarActionPerformed
    private void imprimirCupom(Object c){
        throw new UnsupportedOperationException("Nao suportado.");
        
        
        
    
    }
    
    public void imprimir(String pTexto){
        // \n\r para no no valinha e \f para nova pagina
        try{
            //PEGAR A IMPRESSORA PADRAO
            InputStream prin = new ByteArrayInputStream(pTexto.getBytes());
            DocFlavor docFlavor = DocFlavor.INPUT_STREAM.AUTOSENSE;
            SimpleDoc documentoTexto = new SimpleDoc(prin,docFlavor,null);
            PrintService impressora = PrintServiceLookup.lookupDefaultPrintService();
            //PEGAR A IMPRESSORA PADRAO
            //INFORMA  TIPO DE FOLHA
            PrintRequestAttributeSet printerAttributes = new HashPrintRequestAttributeSet();
            printerAttributes.add(new JobName("Impressão",null));
            printerAttributes.add(OrientationRequested.PORTRAIT);
            printerAttributes.add(MediaSizeName.ISO_A4);
            //INFORMA  TIPO DE FOLHA
            DocPrintJob printJob = impressora.createPrintJob();
            
            try{
                printJob.print(documentoTexto, (PrintRequestAttributeSet) printerAttributes);
                //TENTA IMPRIMIR
            }catch(PrintException e){
                JOptionPane.showMessageDialog(null,"Não foi possivel imprimir","Erro",JOptionPane.ERROR_MESSAGE);
                //MOSTRA MESSAGEM DE ERRO
            }
            prin.close();
            
        }catch(Exception e){
            
        }
        
        
        
    }
    
    public void Procurar(){
    
        pnlClientePedido.setVisible(true);
        pnlPedido.setVisible(false);
        txtPesquisa.enable();
        btnProcurar.enable();
        
        txtNome1234.disable();
        txtTel.disable();
        txtCel.disable();
        txtEnd.disable();
        txtObs.disable();
        btnOk.disable();
        
}
    
    public void Criar(){
        pnlClientePedido.setVisible(true);
             pnlPedido.setVisible(false);
            txtPesquisa.disable();
        btnProcurar.disable();
        
        txtNome1234.enable();
        txtTel.enable();
        txtCel.enable();
        txtEnd.enable();
        txtObs.enable();
        btnOk.enable();
        
    }
    private void btnCliOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliOkActionPerformed
        // TODO add your handling code here:
        
        
        
        if(radioSim.isSelected()){
           Procurar();
            
        }else{
             Criar();
        }

    }//GEN-LAST:event_btnCliOkActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        // TODO add your handling code here:
        ResultSet resultSet = null;
        Statement statement = null;
        String nome = txtPesquisa.getText();

        conexaoSQLite.conectar();

        statement = conexaoSQLite.criarStatement();

        String query = "SELECT * FROM clientes WHERE nome = "+"'"+nome+"'"+";";

        try{

            resultSet = statement.executeQuery(query);
            txtId.setText(resultSet.getString("cod_cliente"));
            txtNome1234.setText(resultSet.getString("nome"));
            txtTel.setText(resultSet.getString("telefone"));
            txtCel.setText(resultSet.getString("celular"));
            txtEnd.setText(resultSet.getString("end"));
            txtObs.setText(resultSet.getString("observacao"));
            
            pedidoC.setCod_user(resultSet.getString("cod_cliente"));
            pedidoC.setNome(resultSet.getString("nome"));
            pedidoC.setTelefone(resultSet.getString("telefone"));
            pedidoC.setCelular(resultSet.getString("celular"));
            pedidoC.setEnd(resultSet.getString("end"));
            pedidoC.setObs(resultSet.getString("observacao"));
            
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Query de pesquisa nao executada.");
        }
        conexaoSQLite.desconectar();

    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        

        pedidoC.setNome(txtNome1234.getText());
        pedidoC.setTelefone(txtTel.getText());
        pedidoC.setCelular(txtCel.getText());
        pedidoC.setEnd(txtEnd.getText());
        pedidoC.setObs(txtObs.getText());

        conexaoSQLite.conectar();

        String sqlInsert = "INSERT INTO clientes("
        + "cod_cliente,"
        + "nome,"
        + "telefone,"
        + "celular,"
        + "end,"
        + "observacao"
        + ") VALUES(null,?,?,?,?,?);";

        PreparedStatement preparedStatement =  conexaoSQLite.criarPreparedStatement(sqlInsert);

        try{

            preparedStatement.setString(1,pedidoC.getNome());
            preparedStatement.setString(2,pedidoC.getTelefone());
            preparedStatement.setString(3,pedidoC.getCelular());
            preparedStatement.setString(4,pedidoC.getEnd());
            preparedStatement.setString(5,pedidoC.getObs());

            
            
            
            int resultado = preparedStatement.executeUpdate();

            if(resultado == 1){
                JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null,"Falha no cadastro.Tente novamente.");
            }

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);

        }finally{
            if(preparedStatement != null){
                try {
                    preparedStatement.close();
                    conexaoSQLite.desconectar();
                    txtNome1234.disable();
                    txtTel.disable();
                    txtCel.disable();
                    txtEnd.disable();
                    txtObs.disable();
                } catch (SQLException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            conexaoSQLite.desconectar();
        }

    }//GEN-LAST:event_btnOkActionPerformed

   public void Limpar(){
                    txtId.setText("ID");
                    txtPesquisa.setText("");
                    txtNome1234.setText("");
                    txtTel.setText("");
                    txtCel.setText("");
                    txtEnd.setText("");
                    txtObs.setText(""); 
   }
    
    private void btnProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsseguirActionPerformed
        // TODO add your handling code here:
        
        addCli(pedidoC.getNome());
        
        pnlClientePedido.setVisible(false);
        pnlPedido.setVisible(true);
        compra.setCliente(pedidoC.getNome());
        Limpar();
        
        
    }//GEN-LAST:event_btnProsseguirActionPerformed
public static String format(float x) {  
    DecimalFormat df = new DecimalFormat("#0.00");  
    return df.format(x);
}
    
    
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
             
            Produto produto = (Produto) boxProd.getSelectedItem();
            vetor[selecionado] = produto.getNome()+" ("+txtQtd.getValue().toString()+")";
            total[selecionado] = produto.getPreco_venda() * (Integer.parseInt(txtQtd.getValue().toString()));
            produtos[selecionado] = " "+produto.getNome()+" ("+txtQtd.getValue().toString()+")"+" ";
            
            
            lista.removeAllElements();
            Float  soma = 0.00f;
          
            for(int c = 0;c < vetor.length;c++){
                lista.addElement(" "+vetor[c]);
                
                if(!(total[c] == null)){
                    soma = soma + Float.parseFloat(total[c].toString());
                    
                    lblTotal.setText(format(soma));
                    String tot = (Float.toString(soma));
                    compra.setValor_compra(tot);
                    
               }
            }     
            
    }//GEN-LAST:event_btnAddActionPerformed

    
    
    
    private void lstProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProdMouseClicked
        // TODO add your handling code here:
        selecionado = lstProd.getSelectedIndex();

    }//GEN-LAST:event_lstProdMouseClicked

    private void btnRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvActionPerformed
        // TODO add your handling code here:
        Produto produto = (Produto) boxProd.getSelectedItem();
        total[selecionado] = 0.00f;
        vetor[selecionado] = " null ";
        produtos[selecionado] = null;
         lista.removeAllElements();
         Float  soma = 0.00f;
         
         for(int c = 0;c < vetor.length;c++){
                lista.addElement(" "+vetor[c]);
                if(!(total[c] == null)){
                    soma = soma + Float.parseFloat(total[c].toString());
                    
                    lblTotal.setText(format(soma));
                    String tot = (Float.toString(soma));
                    compra.setValor_compra(tot);
               }
            }

           System.out.println(compra.getValor_compra());
         
         
    }//GEN-LAST:event_btnRmvActionPerformed

    private void radioCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCartaoActionPerformed
        // TODO add your handling code here:
        txtValor.setVisible(false);
        btnCalc.setVisible(false);
        txtValor.disable();
        btnCalc.disable();
        lblTroco.setText("0,00");
        
        compra.setPagamento("Cartão");
    }//GEN-LAST:event_radioCartaoActionPerformed

    private void radioDinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDinActionPerformed
        // TODO add your handling code here:
        txtValor.setVisible(true);
        btnCalc.setVisible(true);
        txtValor.enable();
        btnCalc.enable();
        
        compra.setPagamento("Dinheiro");
    }//GEN-LAST:event_radioDinActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        Float valor = Float.parseFloat(txtValor.getText().toString());
        Float tot = Float.parseFloat(compra.getValor_compra().toString());
        Float troco =  (valor) - (tot) ;
        System.out.println(tot);
        lblTroco.setText(format(troco));
        if(troco<0.00){
            lblTroco.setText("<html> <span style='color:red'>"+format(troco)+"</span></html>");
        }
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnObsPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObsPedidoActionPerformed
        // TODO add your handling code here:
        pnlObs.setVisible(true);
        pnlPedido.setVisible(false);
        
        
    }//GEN-LAST:event_btnObsPedidoActionPerformed

    private void btnObsOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObsOkActionPerformed
        // TODO add your handling code here:
        compra.setObs(txtObsPedido.getText());
        pnlObs.setVisible(false);
        pnlPedido.setVisible(true);
    }//GEN-LAST:event_btnObsOkActionPerformed

    private void boxProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxProdActionPerformed

    
    public void addCli(String a){
        
         lblCliente.setText(a);

    }
    
    public String getDateTime() {
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    Date date = new Date(System.currentTimeMillis());
    return dateFormat.format(date);
        
    
    }
    public String dataBanco() {
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    Date date = new Date(System.currentTimeMillis());
    return dateFormat.format(date);
        
    
    }
    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new Pedido().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Pedido.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<Object> boxProd;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnCliOk;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnObsOk;
    private javax.swing.JButton btnObsPedido;
    private javax.swing.JButton btnOk;
    public javax.swing.JButton btnProcurar;
    public javax.swing.JButton btnProsseguir;
    private javax.swing.JButton btnRmv;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JList<String> lstProd;
    private javax.swing.JPanel pnlClientePedido;
    private javax.swing.JPanel pnlObs;
    private javax.swing.JPanel pnlPedido;
    private javax.swing.JRadioButton radioCartao;
    private javax.swing.JRadioButton radioDin;
    private javax.swing.JRadioButton radioNao;
    private javax.swing.JRadioButton radioSim;
    private javax.swing.JFormattedTextField txtCel;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JLabel txtId;
    public javax.swing.JTextField txtNome1234;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextArea txtObsPedido;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JSpinner txtQtd;
    private javax.swing.JFormattedTextField txtTel;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
