package taurus;


import conexoes.ConexaoSQLite;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author icest
 */
public class Usuario extends javax.swing.JFrame {
ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
    //UIManager.put("Button.defaultButtonFollowsFocus", Boolean.TRUE);
   // getRootPane().setDefaultButton(btnOK);

    
    
    
    /**
     * Creates new form Usuario
     */
    protected int cod_user;
    protected String nome;
    protected String login;
    protected String senha;
    protected int admin;
    
     public Usuario(){
        initComponents();
        
     }
    
    public int getCod_User() {
        return cod_user;
    }

    public void setCod_User(int cod_user) {
        this.cod_user = cod_user;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public int getAdmin() {
        return admin;
    }

    public void setAdmin(int admin) {
        this.admin = admin;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlLogar = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnOkLogar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlCadastroUsers = new javax.swing.JPanel();
        btnCriarUsuario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSenha1 = new javax.swing.JPasswordField();
        txtLogin1 = new javax.swing.JTextField();
        txtNome1 = new javax.swing.JTextField();
        radioSim1 = new javax.swing.JRadioButton();
        radioNao1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso");
        setResizable(false);
        getContentPane().setLayout(null);

        pnlLogar.setLayout(null);

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        pnlLogar.add(txtLogin);
        txtLogin.setBounds(80, 142, 210, 50);

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        pnlLogar.add(txtSenha);
        txtSenha.setBounds(80, 220, 210, 50);

        jLabel2.setText("Login:");
        pnlLogar.add(jLabel2);
        jLabel2.setBounds(80, 120, 34, 16);

        jLabel3.setText("Senha:");
        pnlLogar.add(jLabel3);
        jLabel3.setBounds(80, 198, 39, 16);

        btnOkLogar.setText("Entrar");
        btnOkLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkLogarActionPerformed(evt);
            }
        });
        btnOkLogar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnOkLogarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnOkLogarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnOkLogarKeyTyped(evt);
            }
        });
        pnlLogar.add(btnOkLogar);
        btnOkLogar.setBounds(122, 288, 122, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/resumo-de-fundo-com-um-desenho-geometrico_1048-1511.jpg"))); // NOI18N
        pnlLogar.add(jLabel1);
        jLabel1.setBounds(-14, -17, 410, 430);

        getContentPane().add(pnlLogar);
        pnlLogar.setBounds(0, 0, 370, 400);

        pnlCadastroUsers.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadastroUsers.setEnabled(false);
        pnlCadastroUsers.setOpaque(false);
        pnlCadastroUsers.setLayout(null);

        btnCriarUsuario.setText("Cadastrar");
        btnCriarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarUsuarioActionPerformed(evt);
            }
        });
        pnlCadastroUsers.add(btnCriarUsuario);
        btnCriarUsuario.setBounds(170, 290, 120, 40);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cadastro de Usuários");
        pnlCadastroUsers.add(jLabel4);
        jLabel4.setBounds(100, 40, 280, 60);

        jLabel5.setText("Nome:");
        pnlCadastroUsers.add(jLabel5);
        jLabel5.setBounds(70, 140, 41, 16);

        jLabel6.setText("Login:");
        pnlCadastroUsers.add(jLabel6);
        jLabel6.setBounds(70, 180, 34, 16);

        jLabel7.setText("Senha:");
        pnlCadastroUsers.add(jLabel7);
        jLabel7.setBounds(70, 220, 39, 20);

        jLabel8.setText("Administrador:");
        pnlCadastroUsers.add(jLabel8);
        jLabel8.setBounds(120, 250, 100, 20);

        txtSenha1.setEnabled(false);
        pnlCadastroUsers.add(txtSenha1);
        txtSenha1.setBounds(120, 210, 250, 30);

        txtLogin1.setEnabled(false);
        pnlCadastroUsers.add(txtLogin1);
        txtLogin1.setBounds(120, 170, 250, 30);

        txtNome1.setEnabled(false);
        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });
        pnlCadastroUsers.add(txtNome1);
        txtNome1.setBounds(120, 130, 250, 30);

        buttonGroup1.add(radioSim1);
        radioSim1.setSelected(true);
        radioSim1.setText("Sim");
        radioSim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSim1ActionPerformed(evt);
            }
        });
        pnlCadastroUsers.add(radioSim1);
        radioSim1.setBounds(220, 250, 47, 24);

        buttonGroup1.add(radioNao1);
        radioNao1.setText("Não");
        radioNao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNao1ActionPerformed(evt);
            }
        });
        pnlCadastroUsers.add(radioNao1);
        radioNao1.setBounds(280, 250, 47, 24);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/resumo-de-fundo-com-um-desenho-geometrico_1048-1511.jpg"))); // NOI18N
        pnlCadastroUsers.add(jLabel9);
        jLabel9.setBounds(-14, -77, 540, 590);

        getContentPane().add(pnlCadastroUsers);
        pnlCadastroUsers.setBounds(-46, -2, 420, 420);

        jMenu1.setText("Opções");

        jMenuItem1.setText("Criar Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Logar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(377, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnOkLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkLogarActionPerformed
        // TODO add your handling code here:
        
        TelaPrincipal tela = new TelaPrincipal();
        
         ResultSet resultSet = null;
        Statement statement = null;
        conexaoSQLite.conectar();
        
       String login = txtLogin.getText();
       String senha = txtSenha.getText();
        
        
        statement = conexaoSQLite.criarStatement();
        
       
        try{

            String query = "SELECT * FROM usuarios WHERE login="+ "'"+ login + "'"+"AND senha ="+"'"+senha+"'"+";";
            
            resultSet = statement.executeQuery(query);
            
            int id = resultSet.getInt("cod_user");            
            String user = (resultSet.getString("login")); 
            String pass = (resultSet.getString("senha")); 
            int admin = resultSet.getInt("admin");  
            
            conexaoSQLite.desconectar();
            if(login.equals(user) && senha.equals(pass)){
                tela.setVisible(true);
                dispose();
                
                Usuario usuario_atual = new Usuario();
                usuario_atual.setCod_User(id);
                usuario_atual.setLogin(user);
                usuario_atual.setSenha(pass);
                usuario_atual.setAdmin(admin);
                
                int i = JOptionPane.showConfirmDialog(null,"Iniciando Jornada de trabalho?");
        
                     if( i  == 0){               
                    Caixa caixa = new Caixa();
                    caixa.RegistroAbre();
        
            }
                
                
            }else{
                JOptionPane.showMessageDialog(null,"Usuario ou senha não reconhecidos. Tente novamente.");
            }
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Usuário nao econtrado.");
        }finally{
            conexaoSQLite.desconectar();
        }
        
        
        
        
    }//GEN-LAST:event_btnOkLogarActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnuSairActionPerformed
    
    
   
    
    
    private void btnOkLogarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnOkLogarKeyTyped
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnOkLogarKeyTyped
      
    private void btnOkLogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnOkLogarKeyPressed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_btnOkLogarKeyPressed

    private void btnOkLogarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnOkLogarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkLogarKeyReleased

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        // TODO add your handling code here:
        btnOkLogar.setMnemonic(Event.ENTER);
	if (evt.getKeyCode() == Event.ENTER) {
	btnOkLogar.doClick();
        
	}
        
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
            pnlLogar.setVisible(false);
            pnlCadastroUsers.setVisible(true);
            
         btnCriarUsuario.enable();
         txtNome1.enable();
         txtLogin1.enable();
         txtSenha1.enable();
         radioSim1.enable();
         radioNao1.enable();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void radioSim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSim1ActionPerformed

    private void radioNao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNao1ActionPerformed

    private void btnCriarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarUsuarioActionPerformed
        // TODO add your handling code here:
      int resposta = JOptionPane.showConfirmDialog( null,"Confirma o cadastro?", "Cadastro",JOptionPane.YES_NO_OPTION);

        if(resposta == 0){
            if((txtNome1.getText().replace(" ","").isEmpty()) || txtSenha1.getText().replace(" ","").isEmpty() || txtLogin1.getText().replace(" ","").isEmpty()){
                JOptionPane.showMessageDialog(null,"Não pode haver campos em branco!");
                txtNome1.setText("");
                txtLogin1.setText("");
                txtSenha1.setText("");
                resposta = 1;
            }else{
                Usuario usuario1 = new Usuario();

                usuario1.setNome(txtNome1.getText());
                usuario1.setLogin(txtLogin1.getText());
                usuario1.setSenha(txtSenha1.getText());

                if(radioNao1.isSelected()){
                    usuario1.setAdmin(0);
                }else{
                    usuario1.setAdmin(1);
                }

                conexaoSQLite.conectar();

                String sqlInsert = "INSERT INTO usuarios("
                + "cod_user,"
                + "nome,"
                + "login,"
                + "senha,"
                + "admin) VALUES(null,?,?,?,?)"
                + ";";

                PreparedStatement preparedStatement =  conexaoSQLite.criarPreparedStatement(sqlInsert);

                try{

                    preparedStatement.setString(1,usuario1.getNome());
                    preparedStatement.setString(2,usuario1.getLogin());
                    preparedStatement.setString(3,usuario1.getSenha());
                    preparedStatement.setInt(4,usuario1.getAdmin());

                    int resultado = preparedStatement.executeUpdate();

                    if(resultado == 1){
                        JOptionPane.showMessageDialog(null,"Usuário cadastrado com sucesso!");
                    }else{
                        JOptionPane.showMessageDialog(null,"Falha no cadastro.Tente novamente.");
                    }

                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Não foi possível cadastrar.");
                }finally{
                    if(preparedStatement != null){
                        try {
                            preparedStatement.close();
                            conexaoSQLite.desconectar();
                            txtNome1.setText("");
                            txtLogin1.setText("");
                            txtSenha1.setText("");
                        } catch (SQLException ex) {
                            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    conexaoSQLite.desconectar();
                }
            }

        }
        
        
        
    }//GEN-LAST:event_btnCriarUsuarioActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        pnlLogar.setVisible(true);
            pnlCadastroUsers.setVisible(false);
            
         btnCriarUsuario.disable();
         txtNome1.disable();
         txtLogin1.disable();
         txtSenha1.disable();
         radioSim1.disable();
         radioNao1.disable();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
        
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        conexaoSQLite.conectar();
        
         CriarBancoSQLite criarBancoSQLite = new CriarBancoSQLite(conexaoSQLite);
        
         criarBancoSQLite.criarTabelaUsuario();
         criarBancoSQLite.criarTabelaClientes();
         criarBancoSQLite.criarTabelaProdutos();
         criarBancoSQLite.criarTabelaDespeza();
         criarBancoSQLite.criarTabelaCaixa();
         criarBancoSQLite.criarTabelaCompra();
         
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarUsuario;
    private javax.swing.JButton btnOkLogar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JPanel pnlCadastroUsers;
    private javax.swing.JPanel pnlLogar;
    private javax.swing.JRadioButton radioNao1;
    private javax.swing.JRadioButton radioSim1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtLogin1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenha1;
    // End of variables declaration//GEN-END:variables
}
